
version: "3.9"

services:
  rabbitmq:
    platform: linux/arm64/v8
    environment:
      - RABBITMQ_DEFAULT_USER=user 
      - RABBITMQ_DEFAULT_PASS=password
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq


volumes:
  rabbitmq_data: